data<-subset(household_power_consumption,household_power_consumption$Date=="1/2/2007" | household_power_consumption$Date=="2/2/2007")
png("plot2.png",width=480,height=480,units="px",bg="white")
datetime<-strptime(paste(data$Date,data$Time,sep=" "),"%d/%m/%Y %H:%M:%S")
plot(datetime,as.numeric(data$Global_active_power),type = "l",xlab="",ylab="Global Active Power (kilowatts")
dev.off() 